#ifndef __DEBUG_VOLUME_BASE_H__
#define __DEBUG_VOLUME_BASE_H__


#define NR_SEGMENTS_ON_HALF_CIRCLE			27
#define NR_SEGMENTS_ON_QUARTER_CIRCLE		(NR_SEGMENTS_ON_HALF_CIRCLE>>1)


#define NR_SEGMENTS_ON_SPHERE		(6*NR_SEGMENTS_ON_HALF_CIRCLE)
#define NR_SEGMENTS_ON_SPOT			(4*(NR_SEGMENTS_ON_HALF_CIRCLE+1))

#define NR_SEGMENTS_ON_WEDGE		(10 + 2*(NR_SEGMENTS_ON_QUARTER_CIRCLE+NR_SEGMENTS_ON_HALF_CIRCLE+NR_SEGMENTS_ON_HALF_CIRCLE))
#define NR_SEGMENTS_ON_CAPSULE		(4 + 8*NR_SEGMENTS_ON_HALF_CIRCLE)



#define MAX_NR_SEGMENTS_ON_ANY_VOLUME		NR_SEGMENTS_ON_CAPSULE



#endif
